[profile.default]
optimizer = true
via_ir = true
evm_version = "cancun"
auto_detect_remappings = false
optimizer_runs = 1_000_000
solc_version = "0.8.28"

[profile.default.optimizer_details]
constantOptimizer = true
yul = true

[profile.deploy]
ffi = true
fs_permissions = [{ access = "read", path = "./image.svg"}]
